name: Build and Deploy Frontend to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: cd frontend && npm ci

    - name: Build
      run: cd frontend && npm run build

    - name: Deploy to Azure Storage
      uses: azure/cli@v1
      with:
        inlineScript: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az storage blob upload-batch -d '$web' --account-name <YOUR_STORAGE_ACCOUNT_NAME> -s frontend/build
